# Generated by Django 4.2.16 on 2024-09-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumExamen', models.IntegerField(verbose_name='Numero de Examen')),
                ('Nombres', models.TextField(max_length=60, verbose_name='Nombres')),
                ('FecExamen', models.DateField(verbose_name='Fecha')),
                ('Resultado', models.TextField(max_length=60, verbose_name='Resultado')),
                ('Descripcion', models.TextField(max_length=60, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name_plural': 'Examens',
            },
        ),
    ]
