# Generated by Django 4.2.16 on 2024-09-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.TextField(max_length=60, verbose_name='Nombres')),
                ('UnidadMedida', models.TextField(max_length=60, verbose_name='UnidadMedida')),
                ('ValorReferenciaMax', models.TextField(max_length=60, verbose_name='ValorReferenciaMax')),
                ('ValorReferenciaMin', models.TextField(max_length=60, verbose_name='ValorReferenciaMin')),
                ('Descripcion', models.TextField(max_length=60, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name_plural': 'Indicadores',
            },
        ),
    ]
