# Generated by Django 4.2.16 on 2024-09-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.TextField(max_length=60, verbose_name='Nombre')),
                ('Descripcion', models.TextField(max_length=60, verbose_name='Descripcion')),
                ('Estatus', models.TextField(max_length=60, verbose_name='Estatus')),
                ('Fecha', models.DateField(verbose_name='Fecha')),
                ('FechaModificacion', models.DateField(verbose_name='FechaModificacion')),
            ],
            options={
                'verbose_name_plural': 'Especialidad',
            },
        ),
    ]
