# Generated by Django 4.2.16 on 2024-09-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleExamenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoExamen', models.CharField(max_length=60, verbose_name='TipoExamen')),
                ('Estado', models.CharField(max_length=60, verbose_name='Estado')),
                ('Costo', models.IntegerField(default=0, verbose_name='Costo')),
                ('Observacion', models.CharField(max_length=60, verbose_name='Observacion')),
            ],
            options={
                'verbose_name_plural': 'DetalleExamenes',
            },
        ),
    ]
