# Generated by Django 4.2.16 on 2024-09-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumCitas', models.CharField(max_length=50, unique=True, verbose_name='NumCitas')),
                ('Fecha', models.DateField(max_length=50, verbose_name='Fecha')),
                ('Razon', models.CharField(max_length=50, verbose_name='Razon')),
                ('Hora', models.DateTimeField(auto_now_add=True, verbose_name='Hora')),
                ('Nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('Estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('Costo', models.FloatField(verbose_name='Costo')),
            ],
            options={
                'verbose_name_plural': 'Consultas',
            },
        ),
    ]
