# Generated by Django 4.2.16 on 2024-09-25 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consultas', '0002_alter_consultas_fecha_alter_consultas_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consultas',
            table=None,
        ),
    ]
