# Generated by Django 4.2.16 on 2024-09-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.TextField(max_length=60, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name_plural': 'Genero',
            },
        ),
    ]
