# Generated by Django 4.2.16 on 2024-09-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=5, unique=True, verbose_name='Codigo')),
                ('Nombres', models.TextField(max_length=50, verbose_name='Nombres')),
                ('Apellidos', models.TextField(max_length=50, verbose_name='Apellidos')),
                ('FecNacimiento', models.DateTimeField(verbose_name='FecNacimiento')),
                ('Direccion', models.TextField(max_length=50, verbose_name='Direccion')),
                ('Especialidad', models.TextField(max_length=50, verbose_name='Especialidad')),
                ('Telefono', models.TextField(max_length=20, verbose_name='Telefono')),
            ],
            options={
                'verbose_name_plural': 'Medico',
            },
        ),
    ]
