# Generated by Django 4.2.16 on 2024-09-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Descripcion', models.TextField(verbose_name='Descripcion')),
                ('NombreGenerico', models.TextField(max_length=50, verbose_name='NombreGenerico')),
                ('Presentacion', models.TextField(max_length=50, verbose_name='Presentacion')),
                ('Contradicciones', models.TextField(max_length=50, verbose_name='Contradicciones')),
                ('EfectosSecundarios', models.TextField(max_length=50, verbose_name='EfectosSecundarios')),
            ],
            options={
                'verbose_name_plural': 'Medicamentos',
            },
        ),
    ]
